# Generated by Django 4.2.1 on 2023-07-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_collection_alter_collection_featured_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='default_image', upload_to='products'),
        ),
    ]
