# Generated by Django 4.2.1 on 2023-08-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='cart',
            new_name='order',
        ),
    ]
